export const sections = [
  {id: 1, name: 'basic'},
  {id: 2, name: 'A-B-C'},
  {id: 3, name: 'books'},
  {id: 4, name: 'other'}
];

export const lessons = [{id: 3,
lesson: '001',
english: 'assign',
course: 'basic',
russian: 'предназначать'
},
{id: 9,
lesson: '001',
english: 'beat',
course: 'basic',
russian: 'бить'
},
{id: 18,
lesson: '001',
english: 'acknowledge',
course: 'basic',
russian: 'признавать'
},
{id: 24,
lesson: '001',
english: 'charge',
course: 'basic',
russian: 'загрузка'
},
{id: 16,
lesson: '001',
english: 'departure',
course: 'basic',
russian: 'отправление'
},
{id: 13,
lesson: '001',
english: 'far',
course: 'basic',
russian: 'далеко'},
{id: 23,
lesson: '001',
english: 'finance',
course: 'basic',
russian: 'финансировать'
},
{id: 10,
lesson: '001',
english: 'golf',
course: 'basic',
russian: 'гольф'
},
{id: 8,
lesson: '001',
english: 'gravity',
course: 'basic',
russian: 'сила тяжести'},
{id: 21,
lesson: '001',
english: 'hostage',
course: 'basic',
russian: 'заложник'
},
{id: 17,
lesson: '001',
english: 'involve',
course: 'basic',
russian: 'вовлекать'
},
{id: 2,
lesson: '001',
english: 'manage',
course: 'basic',
russian: 'управлять, суметь, ухитриться'
},
{id: 5,
lesson: '001',
english: 'number',
course: 'basic',
russian: 'число'},
{id: 12,
lesson: '001',
english: 'outlaw',
course: 'basic',
russian: 'изгнанник'},
{id: 1,
lesson: '001',
english: 'provide',
course: 'basic',
russian: 'обеспечивать'
},
{id: 15,
lesson: '001',
english: 'seal',
course: 'basic',
russian: 'печать'
},
{id: 11,
lesson: '001',
english: 'set',
course: 'basic',
russian: 'комплект, установка'
},
{id: 14,
lesson: '001',
english: 'soar',
course: 'basic',
russian: 'высоко летать'
},
{id: 7,
lesson: '001',
english: 'stem',
course: 'basic',
russian: 'ствол'
},
{id: 22,
lesson: '001',
english: 'thorough',
course: 'basic',
russian: 'добросовестный, основательный'
},
{id: 6,
lesson: '001',
english: 'twin',
course: 'basic',
russian: 'близнец'
},
{id: 20,
lesson: '001',
english: 'uncomfortable',
course: 'basic',
russian: 'неудобный'
},
{id: 19,
lesson: '001',
english: 'wire',
course: 'basic',
russian: 'проволока'
},
{id: 4,
lesson: '001',
english: 'wish',
course: 'basic',
russian: 'желать'
},
{id: 10474,
lesson: '001',
english: 'stomach',
course: 'books',
russian: 'желудок'
},
{id: 10481,
lesson: '001',
english: 'tail',
course: 'books',
russian: 'хвост'
},
{id: 10486,
lesson: '001',
english: 'stair',
course: 'books',
russian: 'ступенька, лестница'
},
{id: 10489,
lesson: '001',
english: 'sidewalk',
course: 'books',
russian: 'тротуар'
},
{id: 10476,
lesson: '001',
english: 'smack',
course: 'books',
russian: 'хлопок, удар'
},
{id: 10484,
lesson: '001',
english: 'porcelain',
course: 'books',
russian: 'фарфор'
},
{id: 10472,
lesson: '001',
english: 'lace',
course: 'books',
russian: 'кружево'
},
{id: 10492,
lesson: '001',
english: 'instant',
course: 'books',
russian: 'мгновение, настойчивый'
},
{id: 10493,
lesson: '001',
english: 'grape',
course: 'books',
russian: 'виноград'
},
{id: 10487,
lesson: '001',
english: 'flake',
course: 'books',
russian: 'хлопья'
},
{id: 10491,
lesson: '001',
english: 'enchant',
course: 'books',
russian: 'очаровывать, околдовывать'
},
{id: 10480,
lesson: '001',
english: 'encourage',
course: 'books',
russian: 'ободрять, поддерживать, поощрять'
},
{id: 10477,
lesson: '001',
english: 'evade',
course: 'books',
russian: 'избегать, уклоняться'
},
{id: 10478,
lesson: '001',
english: 'fade',
course: 'books',
russian: 'обесцвечивать, выцветать'
},
{id: 10485,
lesson: '001',
english: 'fair',
course: 'books',
russian: 'справедливый, прекрасный'
},
{id: 10483,
lesson: '001',
english: 'curtain',
course: 'books',
russian: 'занавеска, штора'
},
{id: 10473,
lesson: '001',
english: 'approach',
course: 'books',
russian: 'приближение, наступление, приближаться'
},
{id: 10495,
lesson: '001',
english: 'blizzard',
course: 'books',
russian: 'буран, вьюга'
},
{id: 10479,
lesson: '001',
english: 'cage',
course: 'books',
russian: 'клетка'
},
{id: 10490,
lesson: '001',
english: 'calm',
course: 'books',
russian: 'спокойный, успокаиваться'
},
{id: 10494,
lesson: '001',
english: 'awkward',
course: 'books',
russian: 'неуклюжий, неловкий'
},
{id: 10475,
lesson: '001',
english: 'backpack',
course: 'books',
russian: 'рюкзак'},
{id: 10488,
lesson: '001',
english: 'bald',
course: 'books',
russian: 'лысый, плешивый'
},
{id: 10482,
lesson: '001',
english: 'bargain',
course: 'books',
russian: 'сделка, соглашение'
}]
